version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "ğŸ†™ ğŸ› ï¸"
    directory: "/"
    labels:
      - "dependencies"
      - "dx"
    open-pull-requests-limit: 10
    reviewers:
      - "RomiC"
    schedule:
      interval: "monthly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "ğŸ†™ ğŸ“¦"
    directory: "/"
    labels:
      - "dependencies"
      - "dx"
    open-pull-requests-limit: 10
    reviewers:
      - "RomiC"
    schedule:
      interval: "monthly"
    versioning-strategy: increase